masterdata:
  appInstallQueryList:
    - name: adminStatus-master-data
      condition: true
      read: Select count(*) from Admin_Status
      sqls:
        - INSERT INTO admin_status (name, status, description, created_date) VALUES ('DB_CREATED', 'completed', 'DB Instance is Created', now());
        - INSERT INTO admin_status (name, status, description, created_date) VALUES ('TABLES_CREATED', 'completed', 'DB Tables are Created', now());
        - INSERT INTO admin_status (name, status, description, created_date) VALUES ('TRIGGER_CREATED', 'pending', 'DB Triggers are Created', now());
        - INSERT INTO admin_status (name, status, description, created_date) VALUES ('MASTER_DATA_CREATED', 'pending', 'Master Data is Created', now());
  appStartQueryList:
    - name: functions-master-data
      condition: false
      read: Select count(*) from Functions
      sqls:
        - INSERT INTO functions (created_date, is_valid, function_name, created_by) VALUES (now(), 1, 'FIND USERS', 1)
        - INSERT INTO functions (created_date, is_valid, function_name, created_by) VALUES (now(), 1, 'CREATE USERS', 1)
    - name: adminStatusUpdate-master-data
      condition: true
      read: Select count(*) from admin_status where name = 'MASTER_DATA_CREATED' and status = 'completed'
      sqls:
        - UPDATE admin_status set status = 'completed', created_date = now() WHERE name = 'MASTER_DATA_CREATED'
        