management:
  security:
    enabled: true
  endpoints:
    health:
      show-components: always
      show-details: always
    info:
      enabled: true
    web:
      exposure:
        include: health,info,beans,env
