package org.openframework.gurukul.pariksha.entity;

// Generated Aug 15, 2012 6:42:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.openframework.commons.jpa.entity.User;

//import com.sm.Usermaster;

/**
 * TrainingStats generated by hbm2java
 */
@Entity
@Table(name = "shiksha_eval_stats")
public class EvalStats implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eval_id", nullable = true)
	private Evaluation evaluation;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eval_start_date_time", length = 19)
	private Date evalStartDateTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eval_end_date_time", length = 19)
	private Date evalEndDateTime;

	@Column(name = "eval_stat_passed")
	private Boolean evaluationStatPassed;

	@Column(name = "eval_stat_status", length = 13)
	private String evaluationStatStatus;

	@Column(name = "eval_stat_result", length = 255)
	private String evaluationStatResult;

	@Column(name = "correct_answer_count")
	private Integer correctAnswerCount;


	@Column(name = "quest_attempt_count")
	private Integer questAttemptCount;

	@Column(name = "eval_quest_count")
	private Integer evalQuestCount;

	public void setUser(User user) {
		this.user = user;
	}

	public EvalStats() {
	}

	public EvalStats(Evaluation evaluation, User user) {
		this.evaluation = evaluation;
		this.user = user;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	public User getUser() {
		return this.user;
	}

	public void setUsermaster(User user) {
		this.user = user;
	}

	public Date getEvalStartDateTime() {
		return this.evalStartDateTime;
	}

	public void setEvalStartDateTime(Date evalStartDateTime) {
		this.evalStartDateTime = evalStartDateTime;
	}

	public Date getEvalEndDateTime() {
		return this.evalEndDateTime;
	}

	public void setEvalEndDateTime(Date evalEndDateTime) {
		this.evalEndDateTime = evalEndDateTime;
	}

	public String getEvaluationStatStatus() {
		return evaluationStatStatus;
	}

	public void setEvaluationStatStatus(String evaluationStatStatus) {
		this.evaluationStatStatus = evaluationStatStatus;
	}

	public String getEvaluationStatResult() {
		return evaluationStatResult;
	}

	public void setEvaluationStatResult(String evaluationStatResult) {
		this.evaluationStatResult = evaluationStatResult;
	}

	public Integer getCorrectAnswerCount() {
		return correctAnswerCount;
	}

	public void setCorrectAnswerCount(Integer correctAnswerCount) {
		this.correctAnswerCount = correctAnswerCount;
	}

	public Integer getQuestAttemptCount() {
		return questAttemptCount;
	}

	public void setQuestAttemptCount(Integer questAttemptCount) {
		this.questAttemptCount = questAttemptCount;
	}

	public Integer getEvalQuestCount() {
		return evalQuestCount;
	}

	public void setEvalQuestCount(Integer evalQuestCount) {
		this.evalQuestCount = evalQuestCount;
	}

	public Boolean getEvaluationStatPassed() {
		return evaluationStatPassed;
	}

	public void setEvaluationStatPassed(Boolean evaluationStatPassed) {
		this.evaluationStatPassed = evaluationStatPassed;
	}

}
