npm i --save @fortawesome/fontawesome-free
npm i --save angular
npm i --save angular-translate
npm i --save angular-translate-loader-url
npm i --save angular-ui-bootstrap
npm i --save angular-ui-router
npm i --save bootstrap
npm i --save jquery
npm i --save popper.js@^1.14.3
